### ISSUE TITLE
Evaluate the new angular 2 router

### ISSUE THREAD

**Issue by sv2dev** [flaviait/ng2-jspm-template#17]
If the router covers everything we use from the ngrx/router, we may use this one instead.

**Comment by DorianGrey** [comment]
Due to the today's commit , ngrx-router is mentioned as deprecated (https://github.com/ngrx/router/commit/07a5991d3ff011526019d74a7c99fa0239f36f8f), i.e. it seems to be required to change the router to properly update our update further. I'll put it on the todo-list in https://github.com/flaviait/ng2-jspm-template/pull/18.

Technically, the new component router is extremely similar to ngrx/router - most of its concepts have been adopted, and as such, it will provide everything we need.

**Comment by sv2dev** [comment]
Resolved by #18
